
import os
import socket
from dotenv import load_dotenv

load_dotenv()

GOOGLE_APIADR = os.getenv('GOOGLE_APIADR')
DEV_HOSTNAME = os.getenv('DEV_HOSTNAME')
isDeveloperPC = True if DEV_HOSTNAME == 'ltone' else False
GOOGLE_APIKEY_PROD = os.getenv('GOOGLE_APIKEY_PROD')
GOOGLE_APIKEY_DEV = os.getenv('GOOGLE_APIKEY_DEV')
GOOGLE_APIKEY = GOOGLE_APIKEY_DEV if socket.gethostname() == DEV_HOSTNAME else GOOGLE_APIKEY_PROD

DEPOT_DB_LOC = os.getenv('DEPOT_DB_LOC')
DEPOTPARK_NOSQL_LOC = os.getenv('DEPOTPARK_NOSQL_LOC')
STATEPARK_NOSQL_LOC = os.getenv('STATEPARK_NOSQL_LOC')
VEHICLES_LOC = os.getenv('VEHICLES_LOC', '../RouteCalc_data/dbs/vehicles.json')
CACHE_LOCATION = os.getenv('CACHE_LOCATION')
LOG_DB_LOCATION = os.getenv('LOG_DB_LOCATION')
PRICE_PREDICTOR_MODEL = os.getenv('PRICE_PREDICTOR_MODEL')

SMS_APIADR = os.getenv('SMS_APIADR')
SMS_APIKEY = os.getenv('SMS_APIKEY')
SMS_ALPHANAME = os.getenv('SMS_ALPHANAME')
BLACKLIST_FILE_LOC = os.getenv('BLACKLIST_FILE_LOC')
SMS_TEXT_REDIAL_PHONE = os.getenv('SMS_TEXT_REDIAL_PHONE')
SMS_BLACKLIST = list()

TELEGRAM_BOT_APIKEY = os.getenv('TELEGRAM_BOT_APIKEY')
TELEGRAM_DIRECT_CHAT_ID = os.getenv('TELEGRAM_DIRECT_CHAT_ID')
TELEGRAM_SILENT_CHAT_ID = os.getenv('TELEGRAM_SILENT_CHAT_ID')
TELEGRAM_LOUD_CHAT_ID = os.getenv('TELEGRAM_LOUD_CHAT_ID')
TELEGRAM_DEVELOPER_CHAT_ID = os.getenv('TELEGRAM_DEVELOPER_CHAT_ID')

LOGLEVEL = os.getenv('LOGLEVEL', 'INFO')
