name: Route Calc CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set DATE_TIME env
      run: echo "DATE_TIME=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ceasione/routecalc:$DATE_TIME

    - name: Run tests
      env:
        GOOGLE_APIKEY_DEV: ${{ secrets.GOOGLE_APIKEY_DEV }}
        SMS_APIKEY: ${{ secrets.SMS_APIKEY }}
        TELEGRAM_BOT_APIKEY: ${{ secrets.TELEGRAM_BOT_APIKEY }}
        TELEGRAM_DIRECT_CHAT_ID: ${{ secrets.TELEGRAM_DIRECT_CHAT_ID }}
        TELEGRAM_SILENT_CHAT_ID: ${{ secrets.TELEGRAM_SILENT_CHAT_ID }}
        TELEGRAM_LOUD_CHAT_ID: ${{ secrets.TELEGRAM_LOUD_CHAT_ID }}
        TELEGRAM_DEVELOPER_CHAT_ID: ${{ secrets.TELEGRAM_DEVELOPER_CHAT_ID }}
      run: |
        docker run -d --rm --name rctest \
        -v temp_volume:/RouteCalc/storage \
        -v /tmp:/tmp/rcsocket \
        --env DEV_MACHINE=true \
        --env LOGLEVEL=DEBUG \
        --env GOOGLE_APIKEY_DEV="$GOOGLE_APIKEY_DEV" \
        --env SMS_APIKEY="$SMS_APIKEY" \
        --env TELEGRAM_BOT_APIKEY="$TELEGRAM_BOT_APIKEY" \
        --env TELEGRAM_DIRECT_CHAT_ID="$TELEGRAM_DIRECT_CHAT_ID" \
        --env TELEGRAM_SILENT_CHAT_ID="$TELEGRAM_SILENT_CHAT_ID" \
        --env TELEGRAM_LOUD_CHAT_ID="$TELEGRAM_LOUD_CHAT_ID" \
        --env TELEGRAM_DEVELOPER_CHAT_ID="$TELEGRAM_DEVELOPER_CHAT_ID" \
        ceasione/routecalc:$DATE_TIME python3 -m app.main
        
        docker exec rctest pytest
        docker stop rctest

    - name: DockerHub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: DockerHub Tag
      run: docker tag ceasione/routecalc:$DATE_TIME ceasione/routecalc:latest

    - name: DockerHub Push
      run: | 
        docker push ceasione/routecalc:$DATE_TIME
        docker push ceasione/routecalc:latest

    - name: Server Deploy
      run: echo ''
