name: Route Calc CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        DATE_TIME=$(date +%s)
        docker build . --file Dockerfile --tag routecalc:$DATE_TIME

    - name: Run tests
      run: |
        docker run -d --rm --name rctest \
        -v temp_volume:/RouteCalc/storage \
        -v /tmp:/tmp/rcsocket \
        --env DEV_MACHINE=true \
        --env LOGLEVEL=DEBUG \
        --env GOOGLE_APIKEY_DEV=${{ secrets.GOOGLE_APIKEY_DEV }} \
        --env SMS_APIKEY=${{ secrets.SMS_APIKEY }} \
        --env SMS_ALPHANAME=${{ secrets.SMS_ALPHANAME }} \
        --env TELEGRAM_BOT_APIKEY=${{ secrets.TELEGRAM_BOT_APIKEY }} \
        --env TELEGRAM_DIRECT_CHAT_ID=${{ secrets.TELEGRAM_DIRECT_CHAT_ID }} \
        --env TELEGRAM_SILENT_CHAT_ID=${{ secrets.TELEGRAM_SILENT_CHAT_ID }} \
        --env TELEGRAM_LOUD_CHAT_ID=${{ secrets.TELEGRAM_LOUD_CHAT_ID }} \
        --env TELEGRAM_DEVELOPER_CHAT_ID=${{ secrets.TELEGRAM_DEVELOPER_CHAT_ID }} \
        routecalc:$DATE_TIME python3 -m app.main
        
        docker exec rctest pytest -m unit
        docker exec rctest pytest -m integration
        docker exec rctest pytest -m network
        docker stop rctest

    - name: DockerHub Login
      run: echo ''
    - name: DockerHub Tag
      run: echo ''
    - name: DockerHub Push
      run: echo ''
    - name: Server Deploy
      run: echo ''
